events{

}

http{

    # creating a variable called backend which will have all the servers where the lb will send the client
    upstream backend{
        server server1:3000;
        server server2:3000;
        server server3:3000;
    }

    server{
        # listening at which port in the container
        listen 80;
        location /{
            # when using as a web server
            # return 200 "hello from nginx";

            # when using as a load balancer 
            # server is the name of container

            # this is working at the port of nginx 
            # not the port on which the server was running previously
            proxy_pass http://backend;

        }
    }
}
